runtime: nodejs14
service: default

handlers:
  - url: /
    secure: always
    redirect_http_response_code: 301
    static_files: build/index.html
    upload: build/index.html
    http_headers:
      Cache-Control: 'private, no-cache, no-store, must-revalidate'
      Expires: '-1'
      Pragma: 'no-cache'

  - url: /(.*\.(gif|png|jpg|css|js|json|svg|pdf))$
    secure: always
    redirect_http_response_code: 301
    static_files: build/\1
    upload: build/(.*)

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: build/index.html
    upload: build/index.html
    http_headers:
      Cache-Control: 'private, no-cache, no-store, must-revalidate'
      Expires: '-1'
      Pragma: 'no-cache'